### ISSUE TITLE
[document]: polygon's inclusion/exclusion rule depending the positveness/negativeness of its area

### ISSUE THREAD

**Issue by kkdd** [d3/d3-geo#103]
A polygon's inclusion/exclusion rule should be described in the document as depending the positveness/negativeness of its area. See the following:

![positiveness](https://user-images.githubusercontent.com/5372642/27509867-eb226abe-5940-11e7-8c8e-18e33bb9d517.jpg)
![negativeness](https://user-images.githubusercontent.com/5372642/27509868-ee05f3d6-5940-11e7-8f47-00a7a47bdf57.jpg)

**Comment by mbostock** [comment]
More of a technicality than the core of this issue, but the area of a spherical polygon is always positive in the domain [0, 4π]. So the instability here is between a polygon that has area ε which is nearly zero, and area 4π - ε.

The issue here is that the [initial](https://github.com/d3/d3-geo/blob/master/src/clip/index.js#L34) [polygonContains](https://github.com/d3/d3-geo/blob/master/src/polygonContains.js) test is returns a different result between the two cases, but either result could be considered valid because the input polygon is invalid.

So, the problem is not that the polygon has negative area in the second case, but that it is self-intersecting in both cases. I believe it is impossible to avoid this instability with self-intersecting spherical polygons; it’s inherently ambiguous which side should be considered the interior.

If you want to submit a pull request documenting that the behavior of self-intersecting polygons is undefined (and should be avoided), that would be fine.

**Comment by kkdd** [comment]
Thank you for your comment.
Is [an instability example](http://bl.ocks.org/kkdd/42efb5de16d09fe92a087ab7ad0a40a9) ("Self-intersecting polygon's area inclusion/exclusion") at the antimeridian the same phenomenon as above?

**Comment by mbostock** [comment]
Those are still self-intersecting polygons, so the behavior is undefined.
