### ISSUE TITLE
Geometries that touch the south pole may be rendered incorrectly.

### ISSUE THREAD

**Issue by kkdd** [d3/d3-geo#105]
Hello,
I have found that a converse including area happens when a polygon touches the south pole in equirectangular projection on a special condition as follows:

![equirectangular1](https://user-images.githubusercontent.com/5372642/28175550-86ed8f44-682f-11e7-8203-32cf9bf5b389.jpg)

![equirectangular2](https://user-images.githubusercontent.com/5372642/28175553-8bcba348-682f-11e7-826d-87f87bdabda4.jpg)

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
  .poly {
  fill: #fa0;
  fill-opacity: .2;
  stroke: #f00;
  stroke-width: .5px;
  }
  .graticule {
  fill: none;
  stroke: #777;
  stroke-width: 0.3px;
  stroke-opacity: 0.5;
  }
  </style>
  <title></title>
</head>
<body>
  <script src="https://d3js.org/d3.v4.min.js"></script> 
  <script>

  var poly = [[0, -30], [120, -30], [0, -90], [0, -30]];
  var width = 600, height = 320, centerProjection = [-80, 0];
  var scaleProj = Math.min(width/2, height)/Math.PI;
  var projection = d3.geoEquirectangular()
  .translate([width/2, height/2]).scale(scaleProj)
  .rotate([-centerProjection[0], -centerProjection[1]]);
  var path = d3.geoPath().projection(projection);
  var graticule = d3.geoGraticule();

  var svg = d3.select("body").append("svg")
    .attr("width", width)
    .attr("height", height)
    .call(d3.drag()
      .subject(function() {var rotate = projection.rotate(); return {x: 2*rotate[0], y: -2*rotate[1]};})
      .on("drag", function() {
        projection.rotate([d3.event.x/2, -d3.event.y/2, projection.rotate()[2]]);
        svg.selectAll("path").attr("d", path);
      }));
      
  svg.append("path")
    .datum({type: "Polygon", coordinates: [poly]})
    .attr("class", "poly")
    .attr("d", path);

  svg.selectAll(".graticule")
    .data(graticule.lines)
    .enter().append("path")
    .attr("class", "graticule")
    .attr("d", path);

  </script>
</body>
</html>
```

**Comment by mbostock** [comment]
Yes, unfortunately this is a consequence of how projection is implemented, and I doubt there is an easy fix for it. You can workaround this issue by avoiding the pole by some small epsilon, for example:

```js
poly = [[0, -30], [120, -30], [0, -89.99999], [0, -30]]
```

**Comment by Fil** [comment]
This issue seems to happen with most (all?) projections that use clipAntimeridian.

The weirdest part of it is that you get different results if you change the _longitude_ of `[0, -90]`, or if you rotate the whole polygon by 80° instead of rotating the projection.

Is this maybe related to the issue that lead to mingle rotate with clipAngle|clipAntimeridian? (See  the discussion at #90.) And to https://github.com/d3/d3-geo/issues/78#issuecomment-275559663 ?

**Comment by Fil** [comment]
Update: the problem lies in the way `polygonContains(poly, point)` checks everything in relation to the South Pole (https://github.com/d3/d3-geo/blob/master/src/polygonContains.js#L56).

When the `point` is at `epsilon` from the South Pole, the result. A solution in that case is to reverse everything and work from the North Pole (#106, check with [this block](https://bl.ocks.org/Fil/6094d3c0c31cc1ffbbc6f2b364634db0)).

I'm not sure it's the best way to do it, maybe there is a better way to fix L56  — but it seems to pass all tests and fixes this issue.

**Comment by kkdd** [comment]
Hello,
Another problematic example:

```
 var points = [[20, 10], [-90, 0], [-160, -70]];
 var poly = points.concat([points[0]]);
```

![polygon](https://user-images.githubusercontent.com/5372642/28746355-c4819330-74c5-11e7-8ad7-5b4f3dfc21c5.jpg)

**Comment by Fil** [comment]
Related issue: `polygonContains(polygon, point)` fails if `point` has a longitude > 180.

**Comment by espinielli** [comment]
Maybe you need to change `pointRadians` from:

```javascript
function pointRadians(point) {
  return [point[0] * radians, point[1] * radians];
}
```

to:

```javascript
function pointRadians(point) {
  return [((point[0] + 180) % 360 - 180) * radians, point[1] * radians];
}
```

or maybe even to:

```javascript
function pointRadians(point) {
  return [
    ((point[0] + 180) % 360 - 180) * radians,
    ((point[1] +  90) % 180 -  90)* radians];
}
```

It could help also #108 (see [1] in [this comment](https://github.com/d3/d3-geo/pull/108#issuecomment-323552103))

**Comment by Fil** [comment]
I believe https://github.com/d3/d3-geo/pull/127 solves this (see http://blockbuilder.org/Fil/f004f37b6d40c848d679e128fab0ea1c ).
