### ISSUE TITLE
Canvas fills wrong side of the Antarctic MultiPolygon

### ISSUE THREAD

**Issue by dongli** [d3/d3-geo#124]
I am using `geoEquirectangular` projection and canvas to map, and I want to fill land with gray color and ocean with blue. But I found that the colors are inverted as shown in the following figure with land blue, after drag, the colors return to normal.
Bad fill color:
![image](https://user-images.githubusercontent.com/367959/33716377-e82deacc-db90-11e7-905b-7704ca01690d.png)
Good fill color:
![image](https://user-images.githubusercontent.com/367959/33716379-ec4c9798-db90-11e7-8288-da0068de7aa5.png)
Any idea?

EDIT:
The only thing that I think may be related is that the Antarctic covers the South Pole. When I remove the main island, the color also returns to normal.

**Comment by mbostock** [comment]
What geometry are you using, and how exactly did you create it? WGS84 geometry needs to be run through [d3.geoStitch](https://github.com/d3/d3-geo-projection/blob/master/README.md#geoStitch) if you want to display it with D3. Make sure you are using the latest d3-geo, d3-geo-projection and topojson (if appropriate), too.

When reporting an issue, please include a link to a live example, preferably on [bl.ocks.org](http://bl.ocks.org) or [RunKit](https://runkit.com/npm/d3), or as a pull request in the [appropriate repository](https://github.com/d3) with new unit tests, that demonstrates that the described behavior is not the [expected behavior](https://github.com/d3/d3/blob/master/API.md). Use only the minimum amount of code necessary to reproduce the unexpected behavior.

A good bug report should **isolate specific methods** that exhibit unexpected behavior and precisely define how expectations were violated. What did you expect the method or methods to do, and how did the observed behavior differ? The more precisely you isolate the issue, the faster I can investigate.

Non-actionable bugs may be temporarily closed until you provide additional information. If you can’t isolate the bug any further, please let me know and I will try to help. However, I beg your patience: I must balance your request against many other responsibilities—fixing other bugs, answering other questions, new features, new documentation, *etc.* Please also consider asking for help on [Stack Overflow](https://stackoverflow.com/tags/d3.js).

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by dongli** [comment]
@mbostock Thanks for your tip! After using `geoStitch`, there is no problem.
