### ISSUE TITLE
polygonContains make my demo wrong

### ISSUE THREAD

**Issue by sknightq** [d3/d3-geo#140]
Hello D3 Team:
    I used OpenLayers and D3 for wind display. It worked great in D3 version3. After D3 version4 publishing, I tried to upgrade from version 3 to version 4. Certainly, I changed the function name like  from `d3.geo.mercator()` to `d3.geoMercator()` . But failed at the end.
[The v3 demo](http://www.sknight.cn:81/d3.v3-map.html) **(correct)**
[The v4 demo](http://www.sknight.cn:81/d3-map.html) **(wrong, the center of the area will be wrong when you scroll mouse to zoom map )**
     I compared much code and found the difference.
     **v3.5.16 :**
     ` return (polarAngle < -ε || polarAngle < ε && d3_geo_areaRingSum < 0) ^ winding & 1;`
     **After v3.5.16 (v3.5.17, v4) :**
    `return (polarAngle < -ε || polarAngle < ε && d3_geo_areaRingSum < -ε) ^ winding & 1;`
     Could anyone explain the changes, please?
     How can I modify my current code if the changes are necessary?
     My code snippets :

     var d3Projection = d3.geoMercator().translate([0, 0]);
     var d3Path = d3.geoPath().projection(d3Projection);
     var pixelBounds = d3Path.bounds(features);  // get wong pixel Bounds in D3 V4
     var pixelBoundsWidth = pixelBounds[1][0] - pixelBounds[0][0];
     var pixelBoundsHeight = pixelBounds[1][1] - pixelBounds[0][1];

This is my [stackoverflow detail](https://stackoverflow.com/questions/49397496/the-change-of-polygon-contain-make-my-demo-wrong-in-d3)

 I will express my sincere thanks to you if you can reply me!

**Comment by Fil** [comment]
The change happened in
https://github.com/d3/d3/commit/eff0a11615ba84c42fe021939007f6b3c629486c

But I'm sorry I don't see how it relates to your use case.

**Comment by sknightq** [comment]
@Fil At first, thanks for your quick replying! What's more, I want to check the data of my topoJSON(contain polygon data) whether is standard. Do you know some tools that can detect my data or some documents that describe the standard?
[my topopJSON](http://www.sknight.cn:81/data/air/ningbo.topo.json)

**Comment by Fil** [comment]
You can test your topojson file with http://mapshaper.org/

You're right, the commit that introduced that _epsilon_ was
https://github.com/d3/d3/commit/dab64a2c662d01765352c0b67fab589210fb26bb#diff-9e52f2bedd0fa6315adc31b0688e35e0

The corresponding issue #2025 has sadly disappeared, but there is a related discussion here https://stackoverflow.com/questions/25895676/how-to-stop-d3-js-from-creating-infinite-areas-from-linear-polygons

It would be very useful to create a simple demo of the bug so we can work on it.

**Comment by sknightq** [comment]
@Fil 
The following is my simple demos：
[v3.5.16](https://jsfiddle.net/sknight127/58g9kvrq/) (correct)
[v4.13.0](https://jsfiddle.net/sknight127/pxbz54wy/) (incorrect)
You will get an incorrect result when using lib after version 3.5.16, the different code was mentioned above.

**Comment by Fil** [comment]
There is no test for (disappeared) issue #2025, which means that if you build d3-geo by reverting dab64a2 on https://github.com/d3/d3-geo/blob/master/src/polygonContains.js#L71 , all the unit tests pass. However, this does not seem to be the solution because…

it appears that two small polygons in your dataset are counter-clockwise, which means that they should be drawn as "the whole planet around the polygon", and their geoBounds are (correctly) evaluated as [-180…180].
See https://beta.observablehq.com/@fil/small-triangle-test for details.

However there seems to be a (different) bug that makes d3.geoPath draw them as if they were  clockwise. https://beta.observablehq.com/@fil/small-circle-test ; my fear is that when we fix this bug, many maps that were ok thanks to that bug will explode.

All in all, I think what we need here is a tool that will marshall any geojson object into a "reasonably usable" form.

**Comment by sknightq** [comment]
@Fil  Thanks for the bug of details and point out the data with counter-clockwise.
Should I modify the data with counter-clockwise to clockwise or waiting for fixing the bug?
