### ISSUE TITLE
Labels surround map extent or for edge graticules

### ISSUE THREAD

**Issue by mattijn** [d3/d3-geo#159]
Often maps have labels surround the extent or at the edges of the graticules:

![labels_extent_graticule](https://user-images.githubusercontent.com/5186265/54455714-d190c580-475c-11e9-8271-f0bea4bafbaf.png)
source images: [Generic Mapping Tools, GMT](http://gmt.soest.hawaii.edu/doc/5.3.2/GMT_Tutorial.html#albers-projection)

For d3-geo I only found this [block](https://bl.ocks.org/piwodlaiwo/ff83126f82d800b7d1f416ac84f120c3) where labels where tried to be placed at the edge of the graticules. But I couldn't find any method how to do this using d3-geo methods or d3 axes/scales.

Hopefully this can be considered as a feature request!

**Comment by mbostock** [comment]
Here’s what I would do:

https://observablehq.com/@d3/graticule-labels

Since d3-geo doesn’t directly handle map rendering (it only does projection and generates paths), I’m not sure what additional API we could offer to help with this. Perhaps d3.geoGraticule could have a method for returning the starts and ends of the meridians and parallels. But I think in any case it wouldn’t help much, since as the notebook above shows, you’d still want to style those labels differently depending on where they are on the map.

**Comment by mattijn** [comment]
Thanks for the response and notebook!
