### ISSUE TITLE
The division between d3-geo and d3-geo-projection

### ISSUE THREAD

**Issue by chrisuehlinger** [d3/d3-geo#19]
So at this point I've gone ahead and made speculative branches for the components that are listed in the issues (circle, area, centroid, bounds). I'm sure those will take some time to review, revise and merge, so in the meantime I've also looked ahead at the parts of `d3.geo` (v3) that are not included in the issues for this repo (or the scaffold of the README).

It seems to me that `d3.geo.path`, `d3.geo.projection` and the "batteries included" projections (like Albers) are being slated for the `d3-geo-projection` module (let me know if I've got any of this wrong). In v4 (or whenever it's ready) will `d3-geo-projection` become a first-class part of D3? Or is the intention to keep it as an optional/auxiliary module?

I forked `d3-geo-projection` just to take a look at its structure, but I'm holding off on getting to work until I better understand our goals.

**Comment by mbostock** [comment]
Thanks for your help! I really appreciate it. I mostly finished with
d3-brush today and I should have time next week to focus on d3-geo.

Yep, that sounds right. Anything projection-related, including d3.geoPath,
should live in d3-geo-projection. So that repo will have both the “core”
projections and the extended ones. I might not include some of the weird
ones in the default build of D3 4.0 (d3/d3) but they’ll all live in
d3-geo-projection. (Of course, others will be able to write their own
projections in other repos thanks to the modular approach.)

**Comment by chrisuehlinger** [comment]
Glad to be of service! If I'm ever getting too far ahead and you want me to slow down, just let me know.

Since it seems like d3-geo-projection is going to be approximately what I expected, I'll work on making a branch that lays the foundation and moves the existing projections over to the new module system and test framework. I'll let you know when that's ready (should be some time next week).
