### ISSUE TITLE
some geojsons are not displayed properly in v2

### ISSUE THREAD

**Issue by donatso** [d3/d3-geo#224]
Updating to v2 shows up strange problem with drawing geojson with geoPath. Most of geojson I tried doesn't draw correctly. In examples below is same code with two versions of d3-geo. on v1 both maps are drawen correctly, on v2 first map is off.

Edit: it seems that problem occurs when calculating the bonds of geojson geoPath.bounds

v1: https://jsfiddle.net/donatso/najf04ve/4/
v2: https://jsfiddle.net/donatso/najf04ve/2/

**Comment by Fil** [comment]
If you log console.log("area", d3.geoArea(props.geometry)) in both versions you will see that the polygons are all covering the sphere. This happens because they are not in the correct winding order.

However there was a bug in d3-geo@1 that was miscalculating the very small polygons, and so the two issues kind of cancelled each other, and you ended up with the (visually) correct result in d3-geo@1.

See also https://github.com/d3/d3-geo/issues/140#issuecomment-396032868 and https://github.com/d3/d3-geo/issues/141

Our current recommendation is to "rewind" the polygons, possibly with https://github.com/Turfjs/turf/tree/master/packages/turf-rewind
