### ISSUE TITLE
Is there a way to get a projection with [lon, lat, radius]?

### ISSUE THREAD

**Issue by jthefang** [d3/d3-geo#230]
I want to get the x,y coordinates for a point on the geo projection, given the longitude, latitude and a radius from the center of the Earth, e.g. the location of a satellite above the Earth. I want to be able to draw something to represent the satellite at that point. I guess in this case it will not be on the surface of the projection but above it.

Is there a way to do this already?

**Comment by jake-low** [comment]
I did [something like this](https://observablehq.com/@jake-low/satellite-ground-track-visualizer) a while ago.

If you have a satellite's position in [lon, lat, altitute] or [lon, lat, radius], then the position on the Earth that's directly below that satellite is simply [lon, lat]. This ignores some subtleties (for example, the Earth isn't perfectly spherical, so it's possible that this point isn't quite the _nearest_ point on the surface to the satellite). But if you stood at [lon, lat], the satellite would be directly above you in the sky.

I may have misunderstood your question; if I have feel free to elaborate and I'll try to be of further help.

**Comment by jake-low** [comment]
Ah, I think I understand now; thanks for clarifying.

The map I made shows the Earth and the satellite in real 3D - it uses [THREE.js](https://threejs.org/) which can render 3D scenes to an HTML5 `<canvas>` element. The projection of that scene (the globe, the satellite, the light effect, etc) is determined by the position of a virtual camera in the THREE.js scene. That virtual camera has a position vector, direction vector, and a field of view, and THREE.js uses all of that to figure out where to draw things in 2D on the screen.

D3's projections work differently. They're mathematical transformations from [lon, lat] to [x, y]. So in a strict sense they're two-dimensional, and only designed for drawing things on the surface of a sphere (such as the Earth). They don't have a well-defined behavior for points that aren't on the surface.

However, I think you can still accomplish what you want to do using just D3.

I'm guessing you're using a projection like [d3.geoOrthographic](https://observablehq.com/@d3/orthographic) or [d3.geoSatellite](https://observablehq.com/@d3/satellite) for which it intuitively feels like drawing things "above" the surface should be possible since it's drawing what _looks_ like a 3D globe. This is actually sort of an illusion. D3 doesn't think of these projections as 3-dimensionsal; they're just functions from [lon, lat] to [x, y] like any other projection. They look 3D to us because they resemble what we'd see with our own eyes or a camera.

If that's the case, I think you can figure out where to draw your satellite by creating a second projection with the same rotation as the one you're using to draw the Earth, but a different `distance` and `scale` (assuming you're using geoSatellite) calculated based on the altitude of the satellite. If you drew all the continents and whatnot using this projection, they'd look like an Earth-shaped shell which encloses the actual Earth, hovering over the surface at a distance of `altitude`. Instead of drawing the whole map again though, you could just use this projection to draw a dot at the [lon, lat] of your satellite, and it will appear to be correctly positioned at [lon, lat, altitude].

Let me know if that sounds useful to you and I can work out what the relationship is between `altitude` and the `distance` and `scale` parameters of the second projection. It has to do with the laws of perspective and I'm not sure what it'd work out to be off the top of my head.

**Comment by Fil** [comment]
For the orthographic projection I think the correct solution is to scale in proportion to (1 + altitude / R).

For the satellite projection, it's a bit more difficult and I'm not sure I'm getting it right: https://observablehq.com/d/4d907c0a4966a206

**Comment by jthefang** [comment]
This is great advice. Thank you both! I think I am able to proceed from here.
