### ISSUE TITLE
Calling geoMercator.center sets the wrong automatic clipExtent.

### ISSUE THREAD

**Issue by jheer** [d3/d3-geo#55]
In a few cases I've encountered geoPath fill errors, with country fills being inappropriately inverted. 

Below is an example that replicates the errors in d3 v4.2.1 and Chrome 51.0.2704.103 (Mac OS). The example assumes `world-50m.json` is on the relative path. Also, see comments below for more.

``` html
<!DOCTYPE html>
<meta charset="utf-8">
<style>

.graticule {
  fill: none;
  stroke: #777;
  stroke-width: .5px;
  stroke-opacity: .5;
}

.land {
  fill: #222;
}

.boundary {
  fill: none;
  stroke: #fff;
  stroke-width: .5px;
}

</style>
<body>
<script src="http://d3js.org/d3.v4.min.js"></script>
<script src="http://d3js.org/topojson.v1.min.js"></script>
<script>

var width = 960,
    height = 500;

var projection = d3.geoMercator()
    .scale(150)
    .translate([width / 2, height / 2])
    .center([-1, 0]);

// This projection also exhibits fill errors
// when used with world-110m.json
// var projection = d3.geoAzimuthalEqualArea()
//     .scale(150)
//     .translate([width / 2, height / 2])
//     .rotate([0, 71, 0]);

var path = d3.geoPath()
    .projection(projection);

var svg = d3.select("body").append("svg")
    .attr("width", width)
    .attr("height", height);

d3.json("world-50m.json", function(error, world) {
  if (error) throw error;

  svg.insert("path", ".graticule")
      .datum(topojson.feature(world, world.objects.land))
      .attr("class", "land")
      .attr("d", path);

  svg.insert("path", ".graticule")
      .datum(topojson.mesh(world, world.objects.countries, function(a, b) { return a !== b; }))
      .attr("class", "boundary")
      .attr("d", path);
});

</script>
```

**Comment by mbostock** [comment]
Related d3/d3#1317.

**Comment by mbostock** [comment]
There are two issues here.

The first is that d3.geoMercator has an automatic internal clipExtent (if the *projection*.clipExtent is null, which is it by default). The code that sets the internal clip extent assumes that the projection center is [0, 0], and if the clip extent is set incorrectly, Bad Things™ can happen with Mercator because it goes to infinity at the poles. You can workaround this issue until it is fixed by using *projection*.translate instead of *projection*.center.

The second is that older versions of world-50m.json and world-110m.json may have had some coordinates slightly outside of [±180°, ±90°], which can causes the interpreted winding order to be inverted. I’ve fixed this in [world-atlas 1.0](https://github.com/topojson/world-atlas) and [d3-geo-projection 1.1.1](https://github.com/d3/d3-geo-projection/releases/tag/v1.1.1):

![screen shot 2016-11-03 at 5 10 33 pm](https://cloud.githubusercontent.com/assets/230541/19990123/7864617c-a1e8-11e6-9060-29b84ac1dd82.png)

I’ve retitled this issue to clarify that it now only applies to the first issue. That’s a lot easier to fix than d3/d3#1317, and I believe that d3/d3#1317 might even be unnecessary thanks to the clamping that is now employed by [d3.geoStitch](https://github.com/d3/d3-geo-projection/blob/master/README.md#geoStitch).

**Comment by apezel** [comment]
The problem seems to happen even if ```projection.center``` is not set. I switched to d3 v4 and i can't get my map to display. Filling is inverted. The problem doesn't seem to be only related to the topojson i use. When i set ```projection.clipExtent```, even the sphere is inverted : 
```
sel.select("#sphere")
        .datum({type: "Sphere"})
        .attr("d", path);
```
It seems that reducing the extent by a 15% resolves the problem with the sphere (but hides some parts of my map).

**Comment by mbostock** [comment]
@apezel You’re probably setting the clip extent outside the defined bounds of the Mercator projection. The Mercator projection extends towards infinity at the poles, but it is only defined on *x* in [*tx* - *k* × π, *tx* + *k* × π] where *tx* is the *x*-translate ([*projection*.translate](https://github.com/d3/d3-geo/blob/master/README.md#projection_translate)) and *k* is the scale ([*projection*.scale](https://github.com/d3/d3-geo/blob/master/README.md#projection_translate)). This is set automatically by default (with a null clip extent), so if you’re setting the clip extent manually, you can break the projection.

For example, this is good:

```js
var projection = d3.geoMercator()
    .scale(150)
    .translate([480, 480])
    .clipExtent([[480 - 150 * Math.PI, 100], [480 + 150 * Math.PI, 860]]);
```

This is bad:

```js
var projection = d3.geoMercator()
    .scale(150)
    .translate([480, 480])
    .clipExtent([[0, 100], [960, 860]]);
```

Of course, it might be possible to clamp a user-specified clip extent automatically, or to apply multiple clip extents so that we don’t have to special-case an automatic clip extent (instead, it would always be applied in addition to an optional user-specified clip extent). However, the former feels a bit hacky, and the latter probably wants something like #78 which is a big undertaking.

**Comment by mbostock** [comment]
I’ve implemented clamping on *x* for Mercator’s clip extent in #88. It should be pretty easy to fix #55, too… I just need to think through how the *projection*.center affects the automatic clip extent and update the math accordingly.

**Comment by mbostock** [comment]
Well, that was a pretty trivial fix. Sorry it took so long!

**Comment by apezel** [comment]
It works perfectly ! Thanks a lot for your quick fix.
