### ISSUE TITLE
comparing projections?

### ISSUE THREAD

**Issue by kodonnell** [d3/d3-geo#92]
This feels like I'm missing something obvious, but I've had a look, and will proceed - if I have missed something, please ignore this!

Say I have two projections, `projA` and `projB` - how do I check if they're the 'same' (which, in my case, means are e.g. both 'geoMercator')? An ugly hack I've found is to compare the string contents of the functions:

```
projA().toString() === projB().toString()
```

You can (ES6 only?) compare the `.name` attributes too.

While these work, neither method is particularly meaningful (within minified code), and e.g. I can't easily find which are instances of 'geoMercator'. (You can do `projA().toString() = d3.geoMercator().toString()` etc.). Is it possible to provide a name attribute, or e.g. override `toString`? Happy to PR if you've got a preference.

Again, sorry if this is a silly question.

**Comment by mbostock** [comment]
There isn’t one. It isn’t a use case I ever felt was necessary, and due to the way projections are implemented as closures, you don’t get one automatically (as you might for a normal class using `instanceof`). If you have a compelling use case, I might consider adding a mechanism for this, but it’s probably more likely that you’ll need to track this information outside the library somehow, say by assigning a name to projection instances when you create them.
